spring:
  datasource:
    url: jdbc:h2:file:./data/demo;MODE=MySQL;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
  h2:
    console:
      enabled: true
      path: /h2-console

spring.servlet.multipart:
  max-file-size: 10MB
  max-request-size: 10MB
